function getPartData(part)
	-- Create an empty table
    local data = {}

    if part==1 then
        -- Assign values to numeric indices for part 1
        data[1] = panel:getModulatorByName("Sample Part-1"):getValue()
        data[2] = panel:getModulatorByName("Sample Hi Cut Part-1"):getValue()
        data[3] = panel:getModulatorByName("Sample Start Point Part-1"):getValue()
        data[4] = panel:getModulatorByName("Sample Length Part-1"):getValue()
        data[5] = panel:getModulatorByName("Reverse Part-1"):getValue()
        data[6] = panel:getModulatorByName("Loop Part-1"):getValue()
        data[7] = panel:getModulatorByName("Pitch Speed Part-1"):getValue()
        data[8] = panel:getModulatorByName("Pitch Eg Int Part-1"):getValue()
        data[9] = panel:getModulatorByName("Pitch Attack Part-1"):getValue()
        data[10] = panel:getModulatorByName("Pitch Decay Part-1"):getValue()
        data[11] = panel:getModulatorByName("Amp Level Part-1"):getValue()
        data[12] = panel:getModulatorByName("Amp Pan Part-1"):getValue()
        data[13] = panel:getModulatorByName("Amp Attack Part-1"):getValue()
        data[14] = panel:getModulatorByName("Amp Decay Part-1"):getValue()
        data[15] = panel:getModulatorByName("Reverb Part-1"):getValue()
    elseif part==2 then
        -- Assign values to numeric indices for part 2
        data[1] = panel:getModulatorByName("Sample Part-2"):getValue()
        data[2] = panel:getModulatorByName("Sample Hi Cut Part-2"):getValue()
        data[3] = panel:getModulatorByName("Sample Start Point Part-2"):getValue()
        data[4] = panel:getModulatorByName("Sample Length Part-2"):getValue()
        data[5] = panel:getModulatorByName("Reverse Part-2"):getValue()
        data[6] = panel:getModulatorByName("Loop Part-2"):getValue()
        data[7] = panel:getModulatorByName("Pitch Speed Part-2"):getValue()
        data[8] = panel:getModulatorByName("Pitch Eg Int Part-2"):getValue()
        data[9] = panel:getModulatorByName("Pitch Attack Part-2"):getValue()
        data[10] = panel:getModulatorByName("Pitch Decay Part-2"):getValue()
        data[11] = panel:getModulatorByName("Amp Level Part-2"):getValue()
        data[12] = panel:getModulatorByName("Amp Pan Part-2"):getValue()
        data[13] = panel:getModulatorByName("Amp Attack Part-2"):getValue()
        data[14] = panel:getModulatorByName("Amp Decay Part-2"):getValue()
        data[15] = panel:getModulatorByName("Reverb Part-2"):getValue()
    elseif part == 3 then
        -- Assign values to numeric indices for part 3
        data[1] = panel:getModulatorByName("Sample Part-3"):getValue()
        data[2] = panel:getModulatorByName("Sample Hi Cut Part-3"):getValue()
        data[3] = panel:getModulatorByName("Sample Start Point Part-3"):getValue()
        data[4] = panel:getModulatorByName("Sample Length Part-3"):getValue()
        data[5] = panel:getModulatorByName("Reverse Part-3"):getValue()
        data[6] = panel:getModulatorByName("Loop Part-3"):getValue()
        data[7] = panel:getModulatorByName("Pitch Speed Part-3"):getValue()
        data[8] = panel:getModulatorByName("Pitch Eg Int Part-3"):getValue()
        data[9] = panel:getModulatorByName("Pitch Attack Part-3"):getValue()
        data[10] = panel:getModulatorByName("Pitch Decay Part-3"):getValue()
        data[11] = panel:getModulatorByName("Amp Level Part-3"):getValue()
        data[12] = panel:getModulatorByName("Amp Pan Part-3"):getValue()
        data[13] = panel:getModulatorByName("Amp Attack Part-3"):getValue()
        data[14] = panel:getModulatorByName("Amp Decay Part-3"):getValue()
        data[15] = panel:getModulatorByName("Reverb Part-3"):getValue()
    elseif part == 4 then
        -- Assign values to numeric indices for part 4
        data[1] = panel:getModulatorByName("Sample Part-4"):getValue()
        data[2] = panel:getModulatorByName("Sample Hi Cut Part-4"):getValue()
        data[3] = panel:getModulatorByName("Sample Start Point Part-4"):getValue()
        data[4] = panel:getModulatorByName("Sample Length Part-4"):getValue()
        data[5] = panel:getModulatorByName("Reverse Part-4"):getValue()
        data[6] = panel:getModulatorByName("Loop Part-4"):getValue()
        data[7] = panel:getModulatorByName("Pitch Speed Part-4"):getValue()
        data[8] = panel:getModulatorByName("Pitch Eg Int Part-4"):getValue()
        data[9] = panel:getModulatorByName("Pitch Attack Part-4"):getValue()
        data[10] = panel:getModulatorByName("Pitch Decay Part-4"):getValue()
        data[11] = panel:getModulatorByName("Amp Level Part-4"):getValue()
        data[12] = panel:getModulatorByName("Amp Pan Part-4"):getValue()
        data[13] = panel:getModulatorByName("Amp Attack Part-4"):getValue()
        data[14] = panel:getModulatorByName("Amp Decay Part-4"):getValue()
        data[15] = panel:getModulatorByName("Reverb Part-4"):getValue()
    elseif part == 5 then
        -- Assign values to numeric indices for part 5
        data[1] = panel:getModulatorByName("Sample Part-5"):getValue()
        data[2] = panel:getModulatorByName("Sample Hi Cut Part-5"):getValue()
        data[3] = panel:getModulatorByName("Sample Start Point Part-5"):getValue()
        data[4] = panel:getModulatorByName("Sample Length Part-5"):getValue()
        data[5] = panel:getModulatorByName("Reverse Part-5"):getValue()
        data[6] = panel:getModulatorByName("Loop Part-5"):getValue()
        data[7] = panel:getModulatorByName("Pitch Speed Part-5"):getValue()
        data[8] = panel:getModulatorByName("Pitch Eg Int Part-5"):getValue()
        data[9] = panel:getModulatorByName("Pitch Attack Part-5"):getValue()
        data[10] = panel:getModulatorByName("Pitch Decay Part-5"):getValue()
        data[11] = panel:getModulatorByName("Amp Level Part-5"):getValue()
        data[12] = panel:getModulatorByName("Amp Pan Part-5"):getValue()
        data[13] = panel:getModulatorByName("Amp Attack Part-5"):getValue()
        data[14] = panel:getModulatorByName("Amp Decay Part-5"):getValue()
        data[15] = panel:getModulatorByName("Reverb Part-5"):getValue()
    elseif part == 6 then
        -- Assign values to numeric indices for part 6
        data[1] = panel:getModulatorByName("Sample Part-6"):getValue()
        data[2] = panel:getModulatorByName("Sample Hi Cut Part-6"):getValue()
        data[3] = panel:getModulatorByName("Sample Start Point Part-6"):getValue()
        data[4] = panel:getModulatorByName("Sample Length Part-6"):getValue()
        data[5] = panel:getModulatorByName("Reverse Part-6"):getValue()
        data[6] = panel:getModulatorByName("Loop Part-6"):getValue()
        data[7] = panel:getModulatorByName("Pitch Speed Part-6"):getValue()
        data[8] = panel:getModulatorByName("Pitch Eg Int Part-6"):getValue()
        data[9] = panel:getModulatorByName("Pitch Attack Part-6"):getValue()
        data[10] = panel:getModulatorByName("Pitch Decay Part-6"):getValue()
        data[11] = panel:getModulatorByName("Amp Level Part-6"):getValue()
        data[12] = panel:getModulatorByName("Amp Pan Part-6"):getValue()
        data[13] = panel:getModulatorByName("Amp Attack Part-6"):getValue()
        data[14] = panel:getModulatorByName("Amp Decay Part-6"):getValue()
        data[15] = panel:getModulatorByName("Reverb Part-6"):getValue()
    elseif part == 7 then
        -- Assign values to numeric indices for part 7
        data[1] = panel:getModulatorByName("Sample Part-7"):getValue()
        data[2] = panel:getModulatorByName("Sample Hi Cut Part-7"):getValue()
        data[3] = panel:getModulatorByName("Sample Start Point Part-7"):getValue()
        data[4] = panel:getModulatorByName("Sample Length Part-7"):getValue()
        data[5] = panel:getModulatorByName("Reverse Part-7"):getValue()
        data[6] = panel:getModulatorByName("Loop Part-7"):getValue()
        data[7] = panel:getModulatorByName("Pitch Speed Part-7"):getValue()
        data[8] = panel:getModulatorByName("Pitch Eg Int Part-7"):getValue()
        data[9] = panel:getModulatorByName("Pitch Attack Part-7"):getValue()
        data[10] = panel:getModulatorByName("Pitch Decay Part-7"):getValue()
        data[11] = panel:getModulatorByName("Amp Level Part-7"):getValue()
        data[12] = panel:getModulatorByName("Amp Pan Part-7"):getValue()
        data[13] = panel:getModulatorByName("Amp Attack Part-7"):getValue()
        data[14] = panel:getModulatorByName("Amp Decay Part-7"):getValue()
        data[15] = panel:getModulatorByName("Reverb Part-7"):getValue()
    elseif part == 8 then
        -- Assign values to numeric indices for part 8
        data[1] = panel:getModulatorByName("Sample Part-8"):getValue()
        data[2] = panel:getModulatorByName("Sample Hi Cut Part-8"):getValue()
        data[3] = panel:getModulatorByName("Sample Start Point Part-8"):getValue()
        data[4] = panel:getModulatorByName("Sample Length Part-8"):getValue()
        data[5] = panel:getModulatorByName("Reverse Part-8"):getValue()
        data[6] = panel:getModulatorByName("Loop Part-8"):getValue()
        data[7] = panel:getModulatorByName("Pitch Speed Part-8"):getValue()
        data[8] = panel:getModulatorByName("Pitch Eg Int Part-8"):getValue()
        data[9] = panel:getModulatorByName("Pitch Attack Part-8"):getValue()
        data[10] = panel:getModulatorByName("Pitch Decay Part-8"):getValue()
        data[11] = panel:getModulatorByName("Amp Level Part-8"):getValue()
        data[12] = panel:getModulatorByName("Amp Pan Part-8"):getValue()
        data[13] = panel:getModulatorByName("Amp Attack Part-8"):getValue()
        data[14] = panel:getModulatorByName("Amp Decay Part-8"):getValue()
        data[15] = panel:getModulatorByName("Reverb Part-8"):getValue()
    elseif part == 9 then
        -- Assign values to numeric indices for part 9
        data[1] = panel:getModulatorByName("Sample Part-9"):getValue()
        data[2] = panel:getModulatorByName("Sample Hi Cut Part-9"):getValue()
        data[3] = panel:getModulatorByName("Sample Start Point Part-9"):getValue()
        data[4] = panel:getModulatorByName("Sample Length Part-9"):getValue()
        data[5] = panel:getModulatorByName("Reverse Part-9"):getValue()
        data[6] = panel:getModulatorByName("Loop Part-9"):getValue()
        data[7] = panel:getModulatorByName("Pitch Speed Part-9"):getValue()
        data[8] = panel:getModulatorByName("Pitch Eg Int Part-9"):getValue()
        data[9] = panel:getModulatorByName("Pitch Attack Part-9"):getValue()
        data[10] = panel:getModulatorByName("Pitch Decay Part-9"):getValue()
        data[11] = panel:getModulatorByName("Amp Level Part-9"):getValue()
        data[12] = panel:getModulatorByName("Amp Pan Part-9"):getValue()
        data[13] = panel:getModulatorByName("Amp Attack Part-9"):getValue()
        data[14] = panel:getModulatorByName("Amp Decay Part-9"):getValue()
        data[15] = panel:getModulatorByName("Reverb Part-9"):getValue()
    elseif part == 10 then
        -- Assign values to numeric indices for part 10
        data[1] = panel:getModulatorByName("Sample Part-10"):getValue()
        data[2] = panel:getModulatorByName("Sample Hi Cut Part-10"):getValue()
        data[3] = panel:getModulatorByName("Sample Start Point Part-10"):getValue()
        data[4] = panel:getModulatorByName("Sample Length Part-10"):getValue()
        data[5] = panel:getModulatorByName("Reverse Part-10"):getValue()
        data[6] = panel:getModulatorByName("Loop Part-10"):getValue()
        data[7] = panel:getModulatorByName("Pitch Speed Part-10"):getValue()
        data[8] = panel:getModulatorByName("Pitch Eg Int Part-10"):getValue()
        data[9] = panel:getModulatorByName("Pitch Attack Part-10"):getValue()
        data[10] = panel:getModulatorByName("Pitch Decay Part-10"):getValue()
        data[11] = panel:getModulatorByName("Amp Level Part-10"):getValue()
        data[12] = panel:getModulatorByName("Amp Pan Part-10"):getValue()
        data[13] = panel:getModulatorByName("Amp Attack Part-10"):getValue()
        data[14] = panel:getModulatorByName("Amp Decay Part-10"):getValue()
        data[15] = panel:getModulatorByName("Reverb Part-10"):getValue()
    end 

    return data

end